#!/bin/sh

set -eux
export DOCKER_BUILDKIT=1
REGISTRY_USERNAME_IMAGE_TAG_INPUT="$(echo "${INPUTS_REGISTRY:-ghcr.io}/${INPUTS_USERNAME:-${GITHUB_REPOSITORY_OWNER}}/${INPUTS_IMAGE:-${GITHUB_REPOSITORY##*/}}:${INPUTS_TAG:-${GITHUB_REF##*/}}" | tr '[:upper:]' '[:lower:]')"
REGISTRY_USERNAME_IMAGE_TAG_TARGET="$(echo "${INPUTS_REGISTRY:-ghcr.io}/${INPUTS_USERNAME:-${GITHUB_REPOSITORY_OWNER}}/${INPUTS_IMAGE:-${GITHUB_REPOSITORY##*/}}:${INPUTS_TAG:-${GITHUB_REF##*/}-stripped}" | tr '[:upper:]' '[:lower:]')"
"${GITHUB_ACTION_PATH}/bin/strip-docker-image" -i "${REGISTRY_USERNAME_IMAGE_TAG_INPUT}" -t "${REGISTRY_USERNAME_IMAGE_TAG_TARGET}" "$@"
docker push "${REGISTRY_USERNAME_IMAGE_TAG_TARGET}"
